### ISSUE TITLE
installing with HACS

### ISSUE THREAD

**Issue by JohanFalk84** [sockless-coding/garo_wallbox#1]
Hello

Can you please help me.

Link to install with HACS?

Config in Configuration.ymal?

Br. Johan Falk

**Comment by sockless-coding** [comment]
Hi,

It should be in the default HACS repository (or be there shortly if it hasn't propagated yet).
But you can add it as a custom repository by entering: https://github.com/sockless-coding/garo_wallbox

It should be listed under integrations i HACS

When it comes to the config its all done from the configuration - integrations menu by using the + at the bottom right.

**Comment by JohanFalk84** [comment]
Now its work from default HACS. Last time i ad it the installation was not i Default som i tried to install if by the link but it dont works when its in Default.

:)

**Comment by matzkarlzzon** [comment]
hello totaly newbie I get the HACS find garo there and then reboted the home assist on request (when it said pending so I gues I sucseeded).
but then if I go to home assistant-> configuration ->  and look under the tab integration it is not there.
above you said that on should push the + add integration but when I search there there is no Garo.
am I on the wrong place or?
