### ISSUE TITLE
Unexpected error creating device

### ISSUE THREAD

**Issue by albatorsk** [sockless-coding/garo_wallbox#11]
I have been using this integration successfully for several months, but today I made the fatal mistake of upgrading my GLBDC-T222WO-A to the latest firmware (from 6.9 I believe, to 1.2.2 (must be a new version numbering scheme)). After doing so, I could still control my wallbox from Home Assistant, up until that I rebooted Home Assistant. Then it would no longer communicate with my wallbox. I decided to remove the integration and set it up again, but now it will not accept the wallbox when trying to add it. A popup is shown with the text: "Aborted. Unexpected error creating device."

The URLs http://xxx.xxx.xxx.xxx:2222/rest/chargebox/status and http://xxx.xxx.xxx.xxx:2222/rest/chargebox/config are accessible and gives me JSON output that can be easily parsed with jq without any errors.

I'm using the Garo integration version 1.0.6 with Home Assistant 2021.3.1.

**Comment by albatorsk** [comment]
The error seems to be related to the **connector** state. When I tried to add the wallbox to the integration in HASS, it was disabled. The state was **DISABLED**. So I enabled the charger, and it's now set to **CHARGING** (as my car is connected and charging), and I could now once again add the wallbox to the HASS integration.

**Comment by maccan-tech** [comment]
This should be solved by #13 
Testing this weekend.
Got a garo wallbox
Modell: GLBDCWM-T222FC
Mjukvaruversion: 1.2.2

**Comment by daunjo** [comment]
Can we expect a release soon with the fix? As soon as I disable the charger throug web GUI it kills the integration.

best regards!

**Comment by sockless-coding** [comment]
I haven't had the time to verify the merge changes more than that they didn't break anything.
But they are included in the v1.0.7

**Comment by daunjo** [comment]
Seems to work, I could add the integration with the charger disabled, and the sensor keeps reacting when changing modes.
Fingers crossed, good work!
