### ISSUE TITLE
RFID id per charging session

### ISSUE THREAD

**Issue by esnil** [sockless-coding/garo_wallbox#15]
Is it possible to add support for quering the id of the RFID used in a charging session?

Would like to build a simple system for charge appropriate for the charging.

**Comment by sockless-coding** [comment]
@esnil if you are still interested, I need some logs I do not have RFID on my box
`http://<ip>:8080/servlet/rest/chargebox/config`
`http://<ip>:8080/servlet/rest/chargebox/status`
`http://<ip>:8080/servlet/rest/chargebox/gcloudreport`

**Comment by esnil** [comment]
Hi!

No, we moved on and chose another brand of charging box.

Thanks for the reply!

I close this now, should have done it long time ago...
