### ISSUE TITLE
Garo wallbox v.1.3.1 breaks integration

### ISSUE THREAD

**Issue by MacKaarstad** [sockless-coding/garo_wallbox#16]
After updating my Garo Wallbox to v.1.3.1, this integration stops working.
Garo has made some changes in the api.

Instead of "http://wallbox-IP:2222/rest/chargebox/status" it is now "http://wallbox-IP:8080/servlet/rest/chargebox/status"

To change the mode of the wallbox to On it is now: http://wallbox-IP:8080/servlet/rest/chargebox/mode/ALWAYS_ON

**Comment by maccan-tech** [comment]
Pull request #17 fixes this. Except mode change.

**Comment by sockless-coding** [comment]
Should be solved now and have backwards compatibility with older versions

**Comment by maccan-tech** [comment]
Entities work but i can not change mode.

**Comment by sockless-coding** [comment]
v1.0.9 addresses the issue with mode selection

**Comment by maccan-tech** [comment]
Thanks, Works great !

**Comment by Johanolofsson82** [comment]
Cant get mode change to work "unknown error"
Set current limit works but not set mode
