### ISSUE TITLE
Energy Reading in HS add up wrongly

### ISSUE THREAD

**Issue by MichaelRV82** [sockless-coding/garo_wallbox#19]
Hi,

this is a great integration. I am experiencing the following problem: when adding the total energy (kwh) as ”track individual energy cunsomptions” in the Energy settings in HS the reading seem to wrongly add up adding the total consumption every day instead of showing the delta.

See screenshot!

Am I doing something wrong?

/Michael
![5F8A6CEA-5053-487F-B329-0E3CA661C31B](https://user-images.githubusercontent.com/92013548/138731147-51a7d295-e918-4d6f-aa82-efc89f457c52.png)

**Comment by sockless-coding** [comment]
Hi @MichaelRV82,
Yeah, that looks off... what version of HA are you on?
Does it show the same numbers if you add it as a Grid consumption?

**Comment by MichaelRV82** [comment]
My core is on Version core-2021.10.6

Also looks off when I selected it for Grid Consumption. See attached.

Any ideas?

![Uploading 9BA9386C-95C4-4B74-BDD0-AB57F0936FB3.png…]()

**Comment by MichaelRV82** [comment]
![8E350415-CC19-4EA6-A19E-94DCBCDBFF3B](https://user-images.githubusercontent.com/92013548/138760193-f248c901-78b5-4487-a4b3-d59656336f16.png)

**Comment by sockless-coding** [comment]
The energy usage looks like it dropped to 0... that could explain the strange reading you are getting because that would cause a delta of what ever your current total is.
What software version are you running on the wallbox? 
There is an energy readout bug in 6.9-146 and earlier.

**Comment by MichaelRV82** [comment]
Good call! I just updated. 1.3.1 now.

see below. Readings still look strange?! Any ideas?

maybe I need to reset the values in HA? How is that done if possible?

Thanks for looking into it!
![4D22AE98-3B99-4D03-851D-7A3F51654CC8](https://user-images.githubusercontent.com/92013548/138766712-a4197e2b-c849-40db-b889-3daab9904891.png)
. 
![3FEDDB5E-2C96-4EC4-82CB-EB9A4ABC18C5](https://user-images.githubusercontent.com/92013548/138766723-a34103a7-d070-46b8-910e-7668717f232f.png)

![6A5E40D4-BFE9-4EDB-8090-ED29AF302531](https://user-images.githubusercontent.com/92013548/138766703-69cb6781-25c1-4d6d-bf40-afda58ba1c37.png)

**Comment by StarkJohan** [comment]
I'm also experiencing the same issue. Haven't had time to look into it yet.
I just checked the db entries for the daily total and from time to time
there is an entry of the all time total in the data set messing up the
daily total just like in your example.

**Comment by sockless-coding** [comment]
@MichaelRV82 the old values under energy will not get fixed. 
You have to reset them, not sure how you can do that. But keep an eye on the new readings while charging in case it spikes again.

**Comment by MichaelRV82** [comment]
It is still behaving strangly:

![46962281-D4B2-4D8F-AC44-0A9B19591C45](https://user-images.githubusercontent.com/92013548/139006352-6b3bdfd2-0047-40ff-bf97-9d4c0c636a29.png)

**Comment by MichaelRV82** [comment]
maybe this is the key:

https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by MichaelRV82** [comment]
after reseting the old values. It keeps doing it. It looks like the consumption is peaking to strange values from time to time:

![32C025DE-135F-4A82-9207-2491016686F0](https://user-images.githubusercontent.com/92013548/139113375-b35af0f8-1481-4d41-9ef0-1a38091e769c.jpeg)

I would really appriciate any ideas to get it fixed!

**Comment by sockless-coding** [comment]
The sensor is set as total increasing, so that is not the issue. There must be something strange coming from the wallbox...
If you look at the Wh sensor does it show the same strange spikes as the kWh one?

**Comment by StarkJohan** [comment]
I'm pretty sure the problem is false data from the wallbox. A workaround is
filtering for outliers in HA. Not the solution but better than not being
able to use the data at all.

**Comment by sockless-coding** [comment]
Yeah, something is off, there was an issue earlier this year... the charge power were returning a massive value every now and again. Guess there is something similar happening from your wallboxes. But I can add a check in case the total delta is larger then 3MWh then ignore that value.

**Comment by StarkJohan** [comment]
In my case the off values is equal to the all time total of the charger
(built in meter).

**Comment by sockless-coding** [comment]
@StarkJohan the Total Energy (kWh) should show the same value as the Metervalue under Energy in the wallbox web UI.

**Comment by sockless-coding** [comment]
I've added a check for invalid total energy values, and released v1.0.11.
Any changes with a delta greater than 500 kWh are discarded.

**Comment by MichaelRV82** [comment]
Thanks!!! just installed it, will keep you posted!
