### ISSUE TITLE
Error in log: Entity sensor.garo_lbk (<class 'custom_components.garo_wallbox.sensor.GaroMainSensor'>) implements device_state_attributes

### ISSUE THREAD

**Issue by ksvard** [sockless-coding/garo_wallbox#24]
After a recent update to Home Assistant I receive this message in the Log:
Entity sensor.garo_lbk (<class 'custom_components.garo_wallbox.sensor.GaroMainSensor'>) implements device_state_attributes. Please report it to the custom component author.

I found a similar error topic here: https://github.com/custom-components/places/issues/31

Possible to fix?

**Comment by sockless-coding** [comment]
Fixed in 2024.9.0
