### ISSUE TITLE
My Garo Wallbox has 2 outlets

### ISSUE THREAD

**Issue by BLLPRE** [sockless-coding/garo_wallbox#25]
It seems like this add-on doesn't work when the Wallbox has 2 outlets, or is it just for me?

**Comment by andersdarljung** [comment]
It won't handle each outlet but you can still use the other funktions, turning off and on both outlets att the same time.
Have been using this integration for 3 years now with glb twin.

**Comment by sockless-coding** [comment]
The new 2024.9.0 version has outlet and twin support
