### ISSUE TITLE
Does this integration support past 1.3.3

### ISSUE THREAD

**Issue by peternorlander** [sockless-coding/garo_wallbox#29]
Thanks for this great integration, love it! My Garo wallbox is running 1.3.3 at the moment but I see there is a new version available. Has anybody upgraded that can confirm this integration still works?

**Comment by protorion** [comment]
I would also like to know this.

**Comment by mickemartinsson** [comment]
I'm running 1.3.6 without any problems.

**Comment by peternorlander** [comment]
> I'm running 1.3.6 without any problems.

Perfect, thanks for answering! :)
