### ISSUE TITLE
Charing current even though charging is disabled

### ISSUE THREAD

**Issue by uwtgomi** [sockless-coding/garo_wallbox#34]
Hi,

I have a load balancer and a GLBDCWM-T222FC.

Even though charging is disabled, the integration shows a non-zero charging current and charging power.
With my smartmeter I figured out that the wallbox simply shows the consumption of the household and not only its own consumption.

1. Is this an issue for the integration or did my electrician simply hook up things wrong?
2. If (1) is yes, should charging current and power simply be forced to 0 as soon as no vehicle is connected or the wallbox is not charging?

Thanks!

**Comment by sockless-coding** [comment]
@uwtgomi Hi, sorry for the late response... It might just be a quirk of the api that it shows the total consumption under the total information.
Could you provide some logs from the box?
`http://<ip>:8080/servlet/rest/chargebox/config`
`http://<ip>:8080/servlet/rest/chargebox/status`
`http://<ip>:8080/servlet/rest/chargebox/lbconfig/false`
`http://<ip>:8080/servlet/rest/chargebox/meterinfo/EXTERNAL`

**Comment by sockless-coding** [comment]
Closing this for now
