### ISSUE TITLE
Change in HA affect the distribution

### ISSUE THREAD

**Issue by ksvard** [sockless-coding/garo_wallbox#35]
HA announced a change in the Command Line integration syntax. This affects the Garo integration as the file /config/garo_chargebox/pkg_garo_chargebox.yaml contains entries for Command Line. An upgrade of the distribution files, with updated yaml-file might be necessary
See more info here: https://community.home-assistant.io/t/configuring-command-line-sensor-using-yaml-has-moved-consult-the-documentation-to-move-your-yaml-configuration-to-integration-key-and-restart-home-assistant-to-fix-this-issue/579429/5

**Comment by sockless-coding** [comment]
This is not the garo_chargebox yaml integration
