### ISSUE TITLE
enhancement: Possibility of changing the "Charge Mode" and "Charge Current".

### ISSUE THREAD

**Issue by maccan-tech** [sockless-coding/garo_wallbox#4]
Hi.

I am looking to buy a Garo wallbox and using this excellent custom component.
I would love to see the possibility of changing the "Charge Mode" and "Charge Current" from inside Home Assistant, 
maybe with 2 services.

Found this in a [forum](https://www.hjemmeautomasjon.no/profile/1498-eskil/?do=content&type=forums_topic_post&change_section=1) , but dont have a Garo yet to test on.

```
curl 'http://192.168.0.138:2222/rest/chargebox/mode' -H 'Content-Type: application/json; charset=UTF-8' --data-binary 'ALWAYS_ON'

curl 'http://192.168.0.138:2222/rest/chargebox/mode' -H 'Content-Type: application/json; charset=UTF-8' --data-binary 'ALWAYS_OFF'

curl 'http://192.168.0.138:2222/rest/chargebox/mode' -H 'Content-Type: application/json; charset=UTF-8' --data-binary 'SCHEMA'

curl 'http://192.168.0.138:2222/rest/chargebox/config' -H 'Content-Type: application/json; charset=UTF-8' --data-binary '{"reducedCurrentInterval":{"chargeLimit":"28"},"master":true}'
```

Med Vänliga Hälsningar
Marcus

**Comment by sockless-coding** [comment]
Hi,

I've had that on my ToDo list, for a long time maybe it's time to do something about it... :)

**Comment by sockless-coding** [comment]
I haven't released a new version but it's now possible to set the Mode of the EVSE and the current limit. 
I'm going to see if I can consolidate the pull request first.

**Comment by maccan-tech** [comment]
Excellent work 👍
Coffee is on its way

**Comment by sockless-coding** [comment]
Cheers ☕ 
I was about time I got around implementing it :)
