### ISSUE TITLE
Unknown error occurred while adding new walbox

### ISSUE THREAD

**Issue by hedkvist** [sockless-coding/garo_wallbox#41]
"Unknown error occurred"

Hello,
I got one garo wallbox working perfekt. 
I bought another one but when i should add it in HA I only get unknown error occurred. 
They both have vlan cards.
I can access it from browser, and also ping it from ha.
Maybe i can't add 2 separate wallboxes in HA? 
GLBDCM-T222FC

if i delete the first one, i can add the other one. But it's not possible to have 2 boxes installed at the same time.

From Errorlog:

  File "/config/custom_components/garo_wallbox/config_flow.py", line 63, in async_step_user
    return await self._create_device(user_input[CONF_HOST], user_input[CONF_NAME])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garo_wallbox/config_flow.py", line 52, in _create_device
    return await self._create_entry(host, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/garo_wallbox/config_flow.py", line 29, in _create_entry
    if entry.data[KEY_IP] == host:
       ~~~~~~~~~~^^^^^^^^
KeyError: 'ip'

**Comment by Monewalker** [comment]
I have the same problem

**Comment by sockless-coding** [comment]
Solved in version 2024.9.0
