### ISSUE TITLE
HomeAssistantType is used, this is a deprecated alias which will be removed in HA Core 

### ISSUE THREAD

**Issue by peternorlander** [sockless-coding/garo_wallbox#42]
Hi,

Thank you for this wonderful integration, have used it everyday for years now! :) I just installed HA 2024.6 and got this message in the log:

"HomeAssistantType was used from garo_wallbox, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'garo_wallbox' custom integration"

No stress for now just wanted to highlight it. Thanks!

Garo Wallbox
v1.0.11

Core
2024.6.4

Supervisor
2024.06.2

Operating System
12.3

Frontend
20240610.1

**Comment by sockless-coding** [comment]
I'm aware of it, it's in the pipeline

**Comment by peternorlander** [comment]
Awesome, thanks. Have a nice weekend!

**Comment by sockless-coding** [comment]
Solved in version 2024.9.0
