### ISSUE TITLE
Can't set mode anymore

### ISSUE THREAD

**Issue by hedkvist** [sockless-coding/garo_wallbox#46]
After the latest update i can't set "mode" by script. 
I might doing it wrong?
It works from the GUI.

I used this script before the update:
data:
  entity_id: sensor.garo1
  mode: "On"
action: garo_wallbox.set_mode

I only get: "Failed to perform the action script/garo_on. 'On' is not a valid Mode"

I tryed this script to:
data:
  entity_id: select.garo1_garo1
  mode: "On"
action: garo_wallbox.set_mode

But it dosen't work either.

The script that worked before the update:
![image](https://github.com/user-attachments/assets/a085b7e2-3d87-4e11-a707-1ccc430e84c5)

Set_current_limit works

**Comment by peterthorvald** [comment]
Yes the latest update screwed up a lot of things. Don’t think you need to change mode via script anymore. You can use the control entity. Also the attribute isn’t “On” anymore, it’s ALWAYS_ON

**Comment by sockless-coding** [comment]
Yes, I managed to break that service call, I'll add some backwards compatibility so On/Off works

**Comment by peterthorvald** [comment]
> Yes, I managed to break that service call, I'll add some backwards compatibility so On/Off works

Sorry, I sounded very ungrateful when in fact I was just frustrated because I use and like your integration very much. I’m sure it will get sorted soon

**Comment by sockless-coding** [comment]
set_mode should work with On/Off in 2024.9.1

Though I would recommend updating to the new mode select
![image](https://github.com/user-attachments/assets/eaef7ea1-94e5-4bf1-879f-110817c72549)

**Comment by hedkvist** [comment]
Thanks!
The new mode select works perfekt!

**Comment by hedkvist** [comment]
> set_mode should work with On/Off in 2024.9.1
> 
> Though I would recommend updating to the new mode select ![image](https://private-user-images.githubusercontent.com/25462432/367593593-eaef7ea1-94e5-4bf1-879f-110817c72549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MjM5NDMsIm5iZiI6MTcyNjQyMzY0MywicGF0aCI6Ii8yNTQ2MjQzMi8zNjc1OTM1OTMtZWFlZjdlYTEtOTRlNS00YmYxLTg3OWYtMTEwODE3YzcyNTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE4MDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0ZGUxMDc0MDllY2VmNjkzOTk2NDFhMGFkY2Y1ZmUyNDhhMjhjNDIzOGUwMjQyNjhjOTI5YjQ1NzgzYWVkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8PBKT91Dlf9S9GHywyRUYkHzP1KCLZONBK7uq4yCOTE)

Thanks!
The new mode select works perfekt!
