### ISSUE TITLE
Changing Cable Lock mode returns error

### ISSUE THREAD

**Issue by ahammas** [sockless-coding/garo_wallbox#47]
I really like this integration. The new set mode (or is it select mode) will make it much easier for new users to get started with controling their Garo. 

I also like that it's now possible to select the lock mode for the cable. However It doesn't work for me. When I go into the integration and select a different lock setting I get the error message "Failed to perform the action select/select_option. list indices must be integers or slices, not str". 

I have set my cable to be locked in the Garo "App" but it would be really handy if I could unlock it from HA so I wouldn't have to go through the Garo "App".

Is it something in the integration or am I doing something wrong?

**Comment by sockless-coding** [comment]
@ahammas Hi, it's the integration I don't have a box with an outlet myself. So I haven't been able to test it. But I'll see if I can figure out where it goes wrong.

**Comment by sockless-coding** [comment]
I found an error, give 2024.9.2 a go and see if it works better.

**Comment by ahammas** [comment]
Wow! Quick action!

It works now, sort of. No error message anymore and it's possible to change the setting but when "Locked" is selected it also checks the "Locked with power loss unlock" option. Unlocked works fine, none of the options are checked if this is selected.  

Almost there :)

**Comment by sockless-coding** [comment]
@ahammas it looks like I've managed to flip the values of Locked and Locked+Power loss unlock

**Comment by sockless-coding** [comment]
Give 2024.9.3 a try, the lock settings "should" be correct now

**Comment by ahammas** [comment]
Great! Now it works as expected. Good job!
