### ISSUE TITLE
Right session energy missing

### ISSUE THREAD

**Issue by OH6HFX** [sockless-coding/garo_wallbox#48]
Can't find entity for right session energy. Left works ok.

**Comment by sockless-coding** [comment]
@OH6HFX what configuration do you have, is it a Twin charger or a Master Slave?

**Comment by OH6HFX** [comment]
This is twin charger. Now I have Garo right total energy chosen and it seems to work, once the car is plugged out the value resets.

**Comment by sockless-coding** [comment]
@OH6HFX I found some resources that were incorrect for the right twin, I will hopefully release a new version later today

**Comment by sockless-coding** [comment]
See if it looks better in 2024.9.3

**Comment by OH6HFX** [comment]
Thanks a lot! Seems that right session energy entity can be found now!
