### ISSUE TITLE
Set mode and limit doesn't work

### ISSUE THREAD

**Issue by andreasropel** [sockless-coding/garo_wallbox#5]
Cannot set neither mode or charging limit. 
I have the latest version installed through HACS. 

I have a Garo box with P/N GLBDCW-T222FC

<img width="450" alt="image" src="https://user-images.githubusercontent.com/54886635/100223372-b5768d00-2f1b-11eb-8ab7-ba40db6e1e37.png">

**Comment by sockless-coding** [comment]
@andreasropel Hi, do you get any log entries when you try to change the mode / limit? 
Also, there is a 30s delay between sensor updates. 

Does the GLBDCW-T222FC have built in WIFI or did you have to get the WIFI module, I cant find the GLBDCW model on garo.se though I see that is a supported model in web-ui of my GLBDCM...

**Comment by andreasropel** [comment]
@sockless-coding I have in my configuration.yaml following line in order to debug:
`custom_components.garo_wallbox: debug`

Nothing in log shown regarding the Wallbox.
The thing is, that it all works but the set mode and set current service.

I do have a wifi module installed in the box, can communicate perfectly and it seems that it is the same commands to set mode and current.

I guess the Wallbox is a fork of the GLBDCM-T222FC.

When I try to run the service, I get this (I know, it's in Swedish):
<img width="467" alt="image" src="https://user-images.githubusercontent.com/54886635/100279051-1f1b8900-2f66-11eb-86b2-3d8698e69b85.png">

**Comment by sockless-coding** [comment]
@andreasropel I wonder if it might just be a bit too picky with the modes try calling it with the following:
entity_id: sensor.garoglb
mode: On


It might not like the ' and the modes are On, Off, Schema

**Comment by andreasropel** [comment]
@sockless-coding That did the trick! 
How about setting the current. 

Trying this: 
`entity_id: sensor.garoglb
limit: 10`

Nothing happens. Where can I verify the limit if not in the status json readout from the box?
`"currentLimit": 16`

**Comment by sockless-coding** [comment]
@andreasropel Ah good that the mode thing got sorted :)

There can be a delay when setting the limit but only a few seconds, do you have a fixed limit or schema set on the box itself?
If you are looking at the json the limit is set by the `reducedCurrentIntervals`

**Comment by andreasropel** [comment]
@sockless-coding Sorted this one as well. 

I needed to set a time period with the limitation in the wallbox GUI first. Now I can change in Home Assistant :)
Thanks for support. 

Closing this issue.
