### ISSUE TITLE
All sensors are unavailable since update this week

### ISSUE THREAD

**Issue by nilaz** [sockless-coding/garo_wallbox#56]
Hi!

I really appreciate that this component is being supported.

I have a Garo twin charger and when I saw that this component was updated I started from scratch. I installed it via HACS into Home Assistant and created an entity. I got both and Energy meter and a Charger.
When I click on the charger entity I can see the name of it plus firmware version, hw version and serial number.
![image](https://github.com/user-attachments/assets/d9ed7dec-538c-46e9-bf06-2b9dbb400cec)

I can see the the long list of sensors but all of them are unavailable.
![image](https://github.com/user-attachments/assets/57a5026b-3add-425b-a5af-a638e3fc54fe)

I have been using older version of this component for years but now I can't get any connection at all.

From a browser I can browse to my twin box so the box works as it should (as I can see it).

What do I do wrong?

**Comment by sockless-coding** [comment]
@nilaz Hi, is there anything in the logs?
If there isn't anything in the normal log, you could try enabling the debug log for the integration.

**Comment by nilaz** [comment]
Here is what I see in the normal log:

> 2024-09-18 18:57:31.474 INFO (MainThread) [homeassistant.setup] Setting up garo_wallbox
> 2024-09-18 18:57:31.856 INFO (MainThread) [homeassistant.components.sensor] Setting up garo_wallbox.sensor
> 2024-09-18 18:57:31.864 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_status
> 2024-09-18 18:57:31.870 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_charging_current
> 2024-09-18 18:57:31.875 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_charging_power
> 2024-09-18 18:57:31.878 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_number_of_phases
> 2024-09-18 18:57:31.884 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_current_limit
> 2024-09-18 18:57:31.888 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_pilot_level
> 2024-09-18 18:57:31.892 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_session_energy
> 2024-09-18 18:57:31.898 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_session_time
> 2024-09-18 18:57:31.902 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_total_energy
> 2024-09-18 18:57:31.906 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_total_energy_kwh
> 2024-09-18 18:57:31.914 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_temperature
> 2024-09-18 18:57:31.917 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_outlet
> 2024-09-18 18:57:31.922 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_charging_current
> 2024-09-18 18:57:31.928 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_charging_power
> 2024-09-18 18:57:31.931 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_number_of_phases
> 2024-09-18 18:57:31.935 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_pilot_level
> 2024-09-18 18:57:31.940 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_session_energy
> 2024-09-18 18:57:31.944 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_session_time
> 2024-09-18 18:57:31.948 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_left_total_energy
> 2024-09-18 18:57:31.954 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_outlet
> 2024-09-18 18:57:31.958 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_charging_current
> 2024-09-18 18:57:31.962 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_charging_power
> 2024-09-18 18:57:31.966 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_number_of_phases
> 2024-09-18 18:57:31.968 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_pilot_level
> 2024-09-18 18:57:31.970 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_session_energy
> 2024-09-18 18:57:31.971 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_session_time
> 2024-09-18 18:57:31.973 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_right_total_energy
> 2024-09-18 18:57:31.974 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_laddbox
> 2024-09-18 18:57:31.975 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.laddbox_schedule
> 2024-09-18 18:57:31.977 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_current_phase_l1
> 2024-09-18 18:57:31.980 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_current_phase_l2
> 2024-09-18 18:57:31.981 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_current_phase_l3
> 2024-09-18 18:57:31.994 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_power_consumption_phase_l1
> 2024-09-18 18:57:31.996 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_power_consumption_phase_l2
> 2024-09-18 18:57:31.997 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_power_consumption_phase_l3
> 2024-09-18 18:57:31.998 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_power_consumption
> 2024-09-18 18:57:32.001 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.garo_wallbox entity: sensor.energy_meter_103155w_energy_consumption_total
> 2024-09-18 18:57:32.010 INFO (MainThread) [homeassistant.components.select] Setting up garo_wallbox.select
> 2024-09-18 18:57:32.011 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.garo_wallbox entity: select.laddbox_laddbox
> 2024-09-18 18:57:32.012 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.garo_wallbox entity: select.laddbox_left_outlet
> 2024-09-18 18:57:32.016 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new select.garo_wallbox entity: select.laddbox_right_outlet
> 2024-09-18 18:57:32.018 INFO (MainThread) [homeassistant.components.number] Setting up garo_wallbox.number
> 2024-09-18 18:57:32.019 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new number.garo_wallbox entity: number.laddbox_current_limit
> 2024-09-18 18:57:32.020 INFO (MainThread) [homeassistant.components.switch] Setting up garo_wallbox.switch
> 2024-09-18 18:57:32.021 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new switch.garo_wallbox entity: switch.laddbox_charge_limiter
> 

After adding this to get debug logging:

I get logs like this:
```
2024-09-18 21:08:51.254 DEBUG (MainThread) [custom_components.garo_wallbox.coordinator] Finished fetching Garo Device Coordinator data in 0.027 seconds (success: True)
2024-09-18 21:08:51.256 DEBUG (MainThread) [custom_components.garo_wallbox.sensor] Updated schedule entries: 0
2024-09-18 21:08:53.189 DEBUG (MainThread) [custom_components.garo_wallbox.coordinator] Finished fetching Garo Meter Coordinator data in 1.951 seconds (success: True)

```
If I look at the sensor for one of the chargers it looks like this:
![image](https://github.com/user-attachments/assets/318b6c21-ded7-489a-8196-2490ac8f9d44)
It says sensor unavailable but there is still data, apparently. So it actually gets values but why does it say unavailable?

**Comment by sockless-coding** [comment]
Might just be a UI issue, have you restarted HA? Or done a hard refresh in the Browser Ctrl+F5

**Comment by nilaz** [comment]
Yes, I restarted HA after adding this row to the logger config:
`    custom_components.garo_wallbox: debug
`
Can I get evem more logs with something more?

**Comment by sockless-coding** [comment]
Since you are getting the `[custom_components.garo_wallbox.coordinator] Finished fetching Garo Device Coordinator data in 0.027 seconds (success: True)` the data from the charger has been read and parsed.

**Comment by nilaz** [comment]
Hard refresh of browser was needed. Thanks for quick help!!!

Keep up the good work!
