### ISSUE TITLE
Charging Power value issue

### ISSUE THREAD

**Issue by maccan-tech** [sockless-coding/garo_wallbox#7]
Hi, thanks for at great custom component.
Finally got my first Garo GLB, and got it working in HA.

I have one issue.
When the charging session has ended the car is pulling 0,8 amps for a short time.
During this time the charging power in Home assistant shows 3628000 W
And i am certain my house can't supply 3,6 MW of power :-)

Tell me if i can help in any way to help get this fixed.

**Comment by sockless-coding** [comment]
Hi @maccan-tech 

I'm not doing any power calculation in the component, so the value must be coming from the charger. Have you checked if there are any pending updates on the charger?

If there isn't any updates, and you can recreate this issue when this reading shows could you try to access:
``http://<ip>:2222/rest/chargebox/status`` and provide me with the read out. There might be something I can check for to handle this :)

**Comment by maccan-tech** [comment]
Hi @sockless-coding 
My Garo charger:
Modell: GLBDCWM-T222FC
Version: 6.9-146 (no update available)

You are correct, the problem seems to be caused by the Garo charger.
Both the _currentChargingCurrent_ and the _currentChargingPower_ show values that is not correct.
My house can not supply 800 Amps or 3628000 W.

> {
"ocppState":null,
"connectedToInternet":false,
"freeCharging":false,
"ocppConnectionState":null,
"connector":"CHARGING_FINISHED",
"mode":"ALWAYS_ON",
"currentLimit":16,
"factoryCurrentLimit":32,
"switchCurrentLimit":16,
"powerMode":"ON",
"currentChargingCurrent":800,
"currentChargingPower":3628000,
"accSessionEnergy":970,
"latestReading":47320,
"chargeStatus":80,
"updateStatus":{"serialsToUpdate":[],"serialsUpdated":[],"currentlyUpdating":-1,"currentProgress":-1,"failedUpdate":0},
"currentTemperature":17,
"slaveControlWarning":false,
"pilotLevel":16,
"sessionStartValue":46350,
"nrOfPhases":1
}

**Comment by sockless-coding** [comment]
@maccan-tech the currentChargingCurrent is in mA, so it's probably ok.
I added an upper limit of 32kW to current power, and if it gets exceeded I return 0 since something is wrong. 
The fix is available in v1.0.4.

I haven't seen this behavior, and I'm on 6.9-146 as well, but I have a GLBDCM-T222FC

**Comment by maccan-tech** [comment]
@sockless-coding thanks a lot. That will be great.
I also sent Garo a email to se what they have to say about the high power value.

**Comment by maccan-tech** [comment]
Got a response from Garo.
It is a bug that will be fixed in a software update.
Your workaround works great until they fix the bug.

**Comment by sockless-coding** [comment]
@maccan-tech Ah good to know they are fixing it :)
