### ISSUE TITLE
All entities Unavailable

### ISSUE THREAD

**Issue by ballez** [sockless-coding/garo_wallbox#9]
Hi!

I got it all to work beautifully but then I had to restart the Wallbox and now it says Unavailable for all entities.

Log readout: 2021-02-16 21:53:56 WARNING (MainThread) [homeassistant.config_entries] Config entry '[Correct Wallbox IP]' for garo_wallbox integration not ready yet.

I tried reinstalling the Integration but still the same.

**Comment by sockless-coding** [comment]
@ballez Hi, sounds like HA is having issues connecting to your wallbox.
Can you verify that the wallbox is responding on that IP by going to `http://[Correct Wallbox IP]:2222/rest/chargebox/status`

**Comment by ballez** [comment]
So it seems:
{"ocppState":null,"connectedToInternet":true,"freeCharging":false,"ocppConnectionState":null,"connector":"CONNECTED","mode":"SCHEMA","currentLimit":13,"factoryCurrentLimit":32,"switchCurrentLimit":13,"powerMode":"OFF","currentChargingCurrent":0,"currentChargingPower":0,"accSessionEnergy":0,"latestReading":505100,"chargeStatus":48,"updateStatus":{"serialsToUpdate":[],"serialsUpdated":[],"currentlyUpdating":-1,"currentProgress":-1,"failedUpdate":0},"currentTemperature":9,"slaveControlWarning":false,"pilotLevel":13,"sessionStartValue":505100,"nrOfPhases":1}

Wallbox information is displayed in HA as well.
![image](https://user-images.githubusercontent.com/78239705/108123200-c6abe180-70a5-11eb-98e2-8d509f55c62e.png)

**Comment by sockless-coding** [comment]
Very strange, the only way I can recreate the issue is when there are connection issues to the wallbox.
Do the entities show up under the device info?

**Comment by ballez** [comment]
Yes, but grayed out.
![image](https://user-images.githubusercontent.com/78239705/108258742-a3923800-7160-11eb-8155-a074207ab4ad.png)

**Comment by ballez** [comment]
The same under Entities, where they're marked "Restored"
![image](https://user-images.githubusercontent.com/78239705/108259879-e99bcb80-7161-11eb-9bc6-ef16ceb69244.png)

Opening one of them and clicking the settings-icon in the top-right corner shows this message:
![image](https://user-images.githubusercontent.com/78239705/108260049-21a30e80-7162-11eb-982b-8e4e70ea7fe5.png)

I'm quite new to HA so the problem can definitely be user-related :)

**Comment by sockless-coding** [comment]
Hmm, you could try the following
Remove the integration
Re-add it and give it a different friendly name, that will force the entities to be recreated

**Comment by ballez** [comment]
Where do I change that name?... Can I change the Wallbox IP address somewhere?

**Comment by sockless-coding** [comment]
@ballez on the HA integration page, when you configure the integration you have the option to set a friendly name.
![image](https://user-images.githubusercontent.com/25462432/108593517-7027f700-7374-11eb-83be-bee7cdf4fe71.png)

**Comment by ballez** [comment]
Managed to remove it completely and install it again, now it works! During my previous attempts I must have missed to remove the integration in HA or something because I never got the opportunity to enter the IP address.

**Comment by sockless-coding** [comment]
Glad to hear its working :)
